# Generated by Django 5.0.6 on 2026-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('slug', models.SlugField(unique=True, verbose_name='URL (slug)')),
                ('short_description', models.CharField(max_length=300, verbose_name='Короткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='robots/', verbose_name='Фото')),
                ('features', models.TextField(default='[]', help_text='Пример: ["Пульсоксиметр", "Видеосвязь 24/7", "Датчик падений"]', verbose_name='Характеристики (JSON-список строк)')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Робот',
                'verbose_name_plural': 'Роботы',
                'ordering': ['-created_at'],
            },
        ),
    ]
