# Generated by Django 6.0.7 on 2026-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text='Показывать в каталоге с пометкой «Скоро», без возможности добавить в корзину.', verbose_name='Скоро в продаже'),
        ),
    ]
